name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Fix missing android folder
        run: |
          mv lib/main.dart /tmp/main.dart
          flutter create. --project-name naija_street_soccer --platforms=android
          mv /tmp/main.dart lib/main.dart
          flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: Naija-Street-Soccer-APK
          path: build/app/outputs/flutter-apk/app-release.apk
